CREATE TABLE `votd` (
 `VerseId` int(11) NOT NULL AUTO_INCREMENT,
 `Reference` varchar(100) NOT NULL,
 `Verse` text NOT NULL,
 PRIMARY KEY (`VerseId`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4